rabbithost: ${CLOUDAMQP_URL}
queuename: ${QUEUE_NAME}
apikey: ${API_KEY}
port: ${PORT}
goenv: ${GO_ENV}
awsregion: ${AWS_REGION}
awsaccesskey: ${AWS_ACCESS_KEY_ID}
awssecret: ${AWS_SECRET_ACCESS_KEY}
spoorhost: https://spoor-api.ft.com/ingest
kinesisstream: 'spoor-egest-uuid'
keenwritekey: ${KEEN_WRITE_KEY}
keenprojectid: ${KEEN_PROJECT_ID}
