rabbithost: ${CLOUDAMQP_URL}
queuename: ${QUEUE_NAME}
apikey: ${API_KEY}
port: ${PORT}
goenv: ${GO_ENV}
awsregion: ${AWS_REGION}
awsaccesskeyid: ${AWS_ACCESS_KEY_ID}
awssecretaccesskey: ${AWS_SECRET_ACCESS_KEY}
kinesisstream: 'spoor-egest-uuid'
